myprog: othello.o game.o space.o main.o
	g++ -o myprog othello.o game.o space.o main.o
othello.o: othello.h othello.cc
	g++ -c othello.cc
game.o: game.h game.cc
	g++ -c game.cc
space.o: space.h space.cc
	g++ -c space.cc
main.o: main.cc
	g++ -c main.cc
